// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    (SELECT COUNT(*) FROM plans p WHERE p.user_id = $1) AS total_plans,
    (SELECT COUNT(*) FROM containers) AS total_containers,
    (SELECT COUNT(*) FROM products) AS total_products,
    (SELECT COALESCE(SUM(quantity), 0) FROM plan_items pi
     JOIN plans p ON pi.plan_id = p.id
     WHERE p.user_id = $1) AS total_items_shipped
`

type GetDashboardStatsRow struct {
	TotalPlans        int64       `json:"total_plans"`
	TotalContainers   int64       `json:"total_containers"`
	TotalProducts     int64       `json:"total_products"`
	TotalItemsShipped interface{} `json:"total_items_shipped"`
}

func (q *Queries) GetDashboardStats(ctx context.Context, userID pgtype.UUID) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats, userID)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalPlans,
		&i.TotalContainers,
		&i.TotalProducts,
		&i.TotalItemsShipped,
	)
	return i, err
}
