// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: containers.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createContainer = `-- name: CreateContainer :one
INSERT INTO containers (name, length_mm, width_mm, height_mm, max_weight_kg)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, length_mm, width_mm, height_mm, max_weight_kg, created_at
`

type CreateContainerParams struct {
	Name        string  `json:"name"`
	LengthMm    float64 `json:"length_mm"`
	WidthMm     float64 `json:"width_mm"`
	HeightMm    float64 `json:"height_mm"`
	MaxWeightKg float64 `json:"max_weight_kg"`
}

func (q *Queries) CreateContainer(ctx context.Context, arg CreateContainerParams) (Container, error) {
	row := q.db.QueryRow(ctx, createContainer,
		arg.Name,
		arg.LengthMm,
		arg.WidthMm,
		arg.HeightMm,
		arg.MaxWeightKg,
	)
	var i Container
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LengthMm,
		&i.WidthMm,
		&i.HeightMm,
		&i.MaxWeightKg,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContainer = `-- name: DeleteContainer :exec
DELETE FROM containers WHERE id = $1
`

func (q *Queries) DeleteContainer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteContainer, id)
	return err
}

const getContainer = `-- name: GetContainer :one
SELECT id, name, length_mm, width_mm, height_mm, max_weight_kg, created_at FROM containers WHERE id = $1
`

func (q *Queries) GetContainer(ctx context.Context, id uuid.UUID) (Container, error) {
	row := q.db.QueryRow(ctx, getContainer, id)
	var i Container
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LengthMm,
		&i.WidthMm,
		&i.HeightMm,
		&i.MaxWeightKg,
		&i.CreatedAt,
	)
	return i, err
}

const listContainers = `-- name: ListContainers :many
SELECT id, name, length_mm, width_mm, height_mm, max_weight_kg, created_at FROM containers ORDER BY created_at DESC
`

func (q *Queries) ListContainers(ctx context.Context) ([]Container, error) {
	rows, err := q.db.Query(ctx, listContainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Container{}
	for rows.Next() {
		var i Container
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LengthMm,
			&i.WidthMm,
			&i.HeightMm,
			&i.MaxWeightKg,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContainer = `-- name: UpdateContainer :one
UPDATE containers
SET name = $2, length_mm = $3, width_mm = $4, height_mm = $5, max_weight_kg = $6
WHERE id = $1
RETURNING id, name, length_mm, width_mm, height_mm, max_weight_kg, created_at
`

type UpdateContainerParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	LengthMm    float64   `json:"length_mm"`
	WidthMm     float64   `json:"width_mm"`
	HeightMm    float64   `json:"height_mm"`
	MaxWeightKg float64   `json:"max_weight_kg"`
}

func (q *Queries) UpdateContainer(ctx context.Context, arg UpdateContainerParams) (Container, error) {
	row := q.db.QueryRow(ctx, updateContainer,
		arg.ID,
		arg.Name,
		arg.LengthMm,
		arg.WidthMm,
		arg.HeightMm,
		arg.MaxWeightKg,
	)
	var i Container
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LengthMm,
		&i.WidthMm,
		&i.HeightMm,
		&i.MaxWeightKg,
		&i.CreatedAt,
	)
	return i, err
}
