// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addPlanItem = `-- name: AddPlanItem :one
INSERT INTO plan_items (plan_id, product_id, quantity)
VALUES ($1, $2, $3)
RETURNING id, plan_id, product_id, quantity
`

type AddPlanItemParams struct {
	PlanID    uuid.UUID `json:"plan_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
}

func (q *Queries) AddPlanItem(ctx context.Context, arg AddPlanItemParams) (PlanItem, error) {
	row := q.db.QueryRow(ctx, addPlanItem, arg.PlanID, arg.ProductID, arg.Quantity)
	var i PlanItem
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.ProductID,
		&i.Quantity,
	)
	return i, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (container_id, status)
VALUES ($1, 'draft')
RETURNING id, container_id, status, created_at, calculated_at
`

func (q *Queries) CreatePlan(ctx context.Context, containerID uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan, containerID)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ContainerID,
		&i.Status,
		&i.CreatedAt,
		&i.CalculatedAt,
	)
	return i, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlan, id)
	return err
}

const deletePlanItem = `-- name: DeletePlanItem :exec
DELETE FROM plan_items WHERE id = $1
`

func (q *Queries) DeletePlanItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlanItem, id)
	return err
}

const deletePlanPlacements = `-- name: DeletePlanPlacements :exec
DELETE FROM placements WHERE plan_id = $1
`

func (q *Queries) DeletePlanPlacements(ctx context.Context, planID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlanPlacements, planID)
	return err
}

const getPlacements = `-- name: GetPlacements :many
SELECT pl.id, pl.plan_id, pl.product_id, pl.pos_x, pl.pos_y, pl.pos_z, pl.rotation, pl.step_number, p.label
FROM placements pl
JOIN products p ON pl.product_id = p.id
WHERE pl.plan_id = $1
ORDER BY pl.step_number ASC
`

type GetPlacementsRow struct {
	ID         uuid.UUID `json:"id"`
	PlanID     uuid.UUID `json:"plan_id"`
	ProductID  uuid.UUID `json:"product_id"`
	PosX       float64   `json:"pos_x"`
	PosY       float64   `json:"pos_y"`
	PosZ       float64   `json:"pos_z"`
	Rotation   int32     `json:"rotation"`
	StepNumber int32     `json:"step_number"`
	Label      string    `json:"label"`
}

func (q *Queries) GetPlacements(ctx context.Context, planID uuid.UUID) ([]GetPlacementsRow, error) {
	rows, err := q.db.Query(ctx, getPlacements, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlacementsRow{}
	for rows.Next() {
		var i GetPlacementsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.ProductID,
			&i.PosX,
			&i.PosY,
			&i.PosZ,
			&i.Rotation,
			&i.StepNumber,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlan = `-- name: GetPlan :one
SELECT id, container_id, status, created_at, calculated_at FROM plans WHERE id = $1
`

func (q *Queries) GetPlan(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ContainerID,
		&i.Status,
		&i.CreatedAt,
		&i.CalculatedAt,
	)
	return i, err
}

const getPlanItem = `-- name: GetPlanItem :one
SELECT pi.id, pi.plan_id, pi.product_id, pi.quantity, p.label, p.length_mm, p.width_mm, p.height_mm, p.weight_kg
FROM plan_items pi
JOIN products p ON pi.product_id = p.id
WHERE pi.id = $1
`

type GetPlanItemRow struct {
	ID        uuid.UUID `json:"id"`
	PlanID    uuid.UUID `json:"plan_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	Label     string    `json:"label"`
	LengthMm  float64   `json:"length_mm"`
	WidthMm   float64   `json:"width_mm"`
	HeightMm  float64   `json:"height_mm"`
	WeightKg  float64   `json:"weight_kg"`
}

func (q *Queries) GetPlanItem(ctx context.Context, id uuid.UUID) (GetPlanItemRow, error) {
	row := q.db.QueryRow(ctx, getPlanItem, id)
	var i GetPlanItemRow
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.ProductID,
		&i.Quantity,
		&i.Label,
		&i.LengthMm,
		&i.WidthMm,
		&i.HeightMm,
		&i.WeightKg,
	)
	return i, err
}

const getPlanItems = `-- name: GetPlanItems :many
SELECT pi.id, pi.plan_id, pi.product_id, pi.quantity, p.label, p.length_mm, p.width_mm, p.height_mm, p.weight_kg
FROM plan_items pi
JOIN products p ON pi.product_id = p.id
WHERE pi.plan_id = $1
`

type GetPlanItemsRow struct {
	ID        uuid.UUID `json:"id"`
	PlanID    uuid.UUID `json:"plan_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	Label     string    `json:"label"`
	LengthMm  float64   `json:"length_mm"`
	WidthMm   float64   `json:"width_mm"`
	HeightMm  float64   `json:"height_mm"`
	WeightKg  float64   `json:"weight_kg"`
}

func (q *Queries) GetPlanItems(ctx context.Context, planID uuid.UUID) ([]GetPlanItemsRow, error) {
	rows, err := q.db.Query(ctx, getPlanItems, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlanItemsRow{}
	for rows.Next() {
		var i GetPlanItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.ProductID,
			&i.Quantity,
			&i.Label,
			&i.LengthMm,
			&i.WidthMm,
			&i.HeightMm,
			&i.WeightKg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT p.id, p.container_id, p.status, p.created_at, p.calculated_at, c.name as container_name
FROM plans p
JOIN containers c ON p.container_id = c.id
ORDER BY p.created_at DESC
`

type ListPlansRow struct {
	ID            uuid.UUID  `json:"id"`
	ContainerID   uuid.UUID  `json:"container_id"`
	Status        string     `json:"status"`
	CreatedAt     *time.Time `json:"created_at"`
	CalculatedAt  *time.Time `json:"calculated_at"`
	ContainerName string     `json:"container_name"`
}

func (q *Queries) ListPlans(ctx context.Context) ([]ListPlansRow, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlansRow{}
	for rows.Next() {
		var i ListPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.ContainerID,
			&i.Status,
			&i.CreatedAt,
			&i.CalculatedAt,
			&i.ContainerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePlacement = `-- name: SavePlacement :exec
INSERT INTO placements (plan_id, product_id, pos_x, pos_y, pos_z, rotation, step_number)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type SavePlacementParams struct {
	PlanID     uuid.UUID `json:"plan_id"`
	ProductID  uuid.UUID `json:"product_id"`
	PosX       float64   `json:"pos_x"`
	PosY       float64   `json:"pos_y"`
	PosZ       float64   `json:"pos_z"`
	Rotation   int32     `json:"rotation"`
	StepNumber int32     `json:"step_number"`
}

func (q *Queries) SavePlacement(ctx context.Context, arg SavePlacementParams) error {
	_, err := q.db.Exec(ctx, savePlacement,
		arg.PlanID,
		arg.ProductID,
		arg.PosX,
		arg.PosY,
		arg.PosZ,
		arg.Rotation,
		arg.StepNumber,
	)
	return err
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans SET container_id = $2
WHERE id = $1
RETURNING id, container_id, status, created_at, calculated_at
`

type UpdatePlanParams struct {
	ID          uuid.UUID `json:"id"`
	ContainerID uuid.UUID `json:"container_id"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan, arg.ID, arg.ContainerID)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ContainerID,
		&i.Status,
		&i.CreatedAt,
		&i.CalculatedAt,
	)
	return i, err
}

const updatePlanItem = `-- name: UpdatePlanItem :one
UPDATE plan_items SET quantity = $2
WHERE id = $1
RETURNING id, plan_id, product_id, quantity
`

type UpdatePlanItemParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) UpdatePlanItem(ctx context.Context, arg UpdatePlanItemParams) (PlanItem, error) {
	row := q.db.QueryRow(ctx, updatePlanItem, arg.ID, arg.Quantity)
	var i PlanItem
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.ProductID,
		&i.Quantity,
	)
	return i, err
}

const updatePlanStatus = `-- name: UpdatePlanStatus :one
UPDATE plans SET status = $2, calculated_at = NOW()
WHERE id = $1
RETURNING id, container_id, status, created_at, calculated_at
`

type UpdatePlanStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlanStatus, arg.ID, arg.Status)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ContainerID,
		&i.Status,
		&i.CreatedAt,
		&i.CalculatedAt,
	)
	return i, err
}
