// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (label, sku, length_mm, width_mm, height_mm, weight_kg)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, label, sku, length_mm, width_mm, height_mm, weight_kg, created_at
`

type CreateProductParams struct {
	Label    string  `json:"label"`
	Sku      string  `json:"sku"`
	LengthMm float64 `json:"length_mm"`
	WidthMm  float64 `json:"width_mm"`
	HeightMm float64 `json:"height_mm"`
	WeightKg float64 `json:"weight_kg"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Label,
		arg.Sku,
		arg.LengthMm,
		arg.WidthMm,
		arg.HeightMm,
		arg.WeightKg,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Sku,
		&i.LengthMm,
		&i.WidthMm,
		&i.HeightMm,
		&i.WeightKg,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, label, sku, length_mm, width_mm, height_mm, weight_kg, created_at FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Sku,
		&i.LengthMm,
		&i.WidthMm,
		&i.HeightMm,
		&i.WeightKg,
		&i.CreatedAt,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT id, label, sku, length_mm, width_mm, height_mm, weight_kg, created_at FROM products WHERE sku = $1
`

func (q *Queries) GetProductBySKU(ctx context.Context, sku string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySKU, sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Sku,
		&i.LengthMm,
		&i.WidthMm,
		&i.HeightMm,
		&i.WeightKg,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, label, sku, length_mm, width_mm, height_mm, weight_kg, created_at FROM products ORDER BY label ASC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Sku,
			&i.LengthMm,
			&i.WidthMm,
			&i.HeightMm,
			&i.WeightKg,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
