// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddPlanItem(ctx context.Context, arg AddPlanItemParams) (PlanItem, error)
	CreateContainer(ctx context.Context, arg CreateContainerParams) (Container, error)
	CreatePlan(ctx context.Context, containerID uuid.UUID) (Plan, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteContainer(ctx context.Context, id uuid.UUID) error
	DeletePlanPlacements(ctx context.Context, planID uuid.UUID) error
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	GetContainer(ctx context.Context, id uuid.UUID) (Container, error)
	GetPlacements(ctx context.Context, planID uuid.UUID) ([]GetPlacementsRow, error)
	GetPlan(ctx context.Context, id uuid.UUID) (Plan, error)
	GetPlanItems(ctx context.Context, planID uuid.UUID) ([]GetPlanItemsRow, error)
	GetProduct(ctx context.Context, id uuid.UUID) (Product, error)
	GetProductBySKU(ctx context.Context, sku string) (Product, error)
	ListContainers(ctx context.Context) ([]Container, error)
	ListProducts(ctx context.Context) ([]Product, error)
	SavePlacement(ctx context.Context, arg SavePlacementParams) error
	UpdateContainer(ctx context.Context, arg UpdateContainerParams) (Container, error)
	UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) (Plan, error)
}

var _ Querier = (*Queries)(nil)
