// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (
    token,
    user_id,
    workspace_id,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateRefreshTokenParams struct {
	Token       string     `json:"token"`
	UserID      uuid.UUID  `json:"user_id"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.Token,
		arg.UserID,
		arg.WorkspaceID,
		arg.ExpiresAt,
	)
	return err
}

const getPermissionsByRole = `-- name: GetPermissionsByRole :many
SELECT p.name
FROM permissions p
JOIN role_permissions rp ON p.permission_id = rp.permission_id
JOIN roles r ON rp.role_id = r.role_id
WHERE r.name = $1
`

func (q *Queries) GetPermissionsByRole(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.Query(ctx, getPermissionsByRole, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT
    user_id,
    workspace_id,
    expires_at,
    revoked_at
FROM refresh_tokens
WHERE token = $1
`

type GetRefreshTokenRow struct {
	UserID      uuid.UUID  `json:"user_id"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
	ExpiresAt   *time.Time `json:"expires_at"`
	RevokedAt   time.Time  `json:"revoked_at"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, token)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.UserID,
		&i.WorkspaceID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
DELETE FROM refresh_tokens 
WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, token)
	return err
}

const updateRefreshTokenWorkspace = `-- name: UpdateRefreshTokenWorkspace :exec
UPDATE refresh_tokens
SET
    workspace_id = $2,
    updated_at = NOW()
WHERE token = $1
`

type UpdateRefreshTokenWorkspaceParams struct {
	Token       string     `json:"token"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateRefreshTokenWorkspace(ctx context.Context, arg UpdateRefreshTokenWorkspaceParams) error {
	_, err := q.db.Exec(ctx, updateRefreshTokenWorkspace, arg.Token, arg.WorkspaceID)
	return err
}
