// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: container.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContainer = `-- name: CreateContainer :one
INSERT INTO containers (
    workspace_id,
    name,
    inner_length_mm,
    inner_width_mm,
    inner_height_mm,
    max_weight_kg,
    description
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING container_id, name, inner_length_mm, inner_width_mm, inner_height_mm, max_weight_kg, description, created_at, updated_at, workspace_id
`

type CreateContainerParams struct {
	WorkspaceID   *uuid.UUID     `json:"workspace_id"`
	Name          string         `json:"name"`
	InnerLengthMm pgtype.Numeric `json:"inner_length_mm"`
	InnerWidthMm  pgtype.Numeric `json:"inner_width_mm"`
	InnerHeightMm pgtype.Numeric `json:"inner_height_mm"`
	MaxWeightKg   pgtype.Numeric `json:"max_weight_kg"`
	Description   *string        `json:"description"`
}

func (q *Queries) CreateContainer(ctx context.Context, arg CreateContainerParams) (Container, error) {
	row := q.db.QueryRow(ctx, createContainer,
		arg.WorkspaceID,
		arg.Name,
		arg.InnerLengthMm,
		arg.InnerWidthMm,
		arg.InnerHeightMm,
		arg.MaxWeightKg,
		arg.Description,
	)
	var i Container
	err := row.Scan(
		&i.ContainerID,
		&i.Name,
		&i.InnerLengthMm,
		&i.InnerWidthMm,
		&i.InnerHeightMm,
		&i.MaxWeightKg,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const deleteContainer = `-- name: DeleteContainer :exec
DELETE FROM containers
WHERE container_id = $1
  AND workspace_id = $2
`

type DeleteContainerParams struct {
	ContainerID uuid.UUID  `json:"container_id"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteContainer(ctx context.Context, arg DeleteContainerParams) error {
	_, err := q.db.Exec(ctx, deleteContainer, arg.ContainerID, arg.WorkspaceID)
	return err
}

const getContainer = `-- name: GetContainer :one
SELECT container_id, name, inner_length_mm, inner_width_mm, inner_height_mm, max_weight_kg, description, created_at, updated_at, workspace_id
FROM containers
WHERE container_id = $1
  AND workspace_id = $2
`

type GetContainerParams struct {
	ContainerID uuid.UUID  `json:"container_id"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetContainer(ctx context.Context, arg GetContainerParams) (Container, error) {
	row := q.db.QueryRow(ctx, getContainer, arg.ContainerID, arg.WorkspaceID)
	var i Container
	err := row.Scan(
		&i.ContainerID,
		&i.Name,
		&i.InnerLengthMm,
		&i.InnerWidthMm,
		&i.InnerHeightMm,
		&i.MaxWeightKg,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const listContainers = `-- name: ListContainers :many
SELECT container_id, name, inner_length_mm, inner_width_mm, inner_height_mm, max_weight_kg, description, created_at, updated_at, workspace_id
FROM containers
WHERE workspace_id = $1
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListContainersParams struct {
	WorkspaceID *uuid.UUID `json:"workspace_id"`
	Limit       int32      `json:"limit"`
	Offset      int32      `json:"offset"`
}

func (q *Queries) ListContainers(ctx context.Context, arg ListContainersParams) ([]Container, error) {
	rows, err := q.db.Query(ctx, listContainers, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Container
	for rows.Next() {
		var i Container
		if err := rows.Scan(
			&i.ContainerID,
			&i.Name,
			&i.InnerLengthMm,
			&i.InnerWidthMm,
			&i.InnerHeightMm,
			&i.MaxWeightKg,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContainer = `-- name: UpdateContainer :exec
UPDATE containers
SET
    name = $3,
    inner_length_mm = $4,
    inner_width_mm = $5,
    inner_height_mm = $6,
    max_weight_kg = $7,
    description = $8,
    updated_at = NOW()
WHERE container_id = $1
  AND workspace_id = $2
`

type UpdateContainerParams struct {
	ContainerID   uuid.UUID      `json:"container_id"`
	WorkspaceID   *uuid.UUID     `json:"workspace_id"`
	Name          string         `json:"name"`
	InnerLengthMm pgtype.Numeric `json:"inner_length_mm"`
	InnerWidthMm  pgtype.Numeric `json:"inner_width_mm"`
	InnerHeightMm pgtype.Numeric `json:"inner_height_mm"`
	MaxWeightKg   pgtype.Numeric `json:"max_weight_kg"`
	Description   *string        `json:"description"`
}

func (q *Queries) UpdateContainer(ctx context.Context, arg UpdateContainerParams) error {
	_, err := q.db.Exec(ctx, updateContainer,
		arg.ContainerID,
		arg.WorkspaceID,
		arg.Name,
		arg.InnerLengthMm,
		arg.InnerWidthMm,
		arg.InnerHeightMm,
		arg.MaxWeightKg,
		arg.Description,
	)
	return err
}
