// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForCreatePlanPlacement implements pgx.CopyFromSource.
type iteratorForCreatePlanPlacement struct {
	rows                 []CreatePlanPlacementParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePlanPlacement) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePlanPlacement) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ResultID,
		r.rows[0].ItemID,
		r.rows[0].PosX,
		r.rows[0].PosY,
		r.rows[0].PosZ,
		r.rows[0].RotationCode,
		r.rows[0].StepNumber,
	}, nil
}

func (r iteratorForCreatePlanPlacement) Err() error {
	return nil
}

func (q *Queries) CreatePlanPlacement(ctx context.Context, arg []CreatePlanPlacementParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"plan_placements"}, []string{"result_id", "item_id", "pos_x", "pos_y", "pos_z", "rotation_code", "step_number"}, &iteratorForCreatePlanPlacement{rows: arg})
}
