// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package store

import (
	"context"
)

const countActivePlans = `-- name: CountActivePlans :one
SELECT COUNT(*) FROM load_plans WHERE status NOT IN ('COMPLETED', 'FAILED')
`

func (q *Queries) CountActivePlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompletedPlans = `-- name: CountCompletedPlans :one
SELECT COUNT(*) FROM load_plans WHERE status = 'COMPLETED'
`

func (q *Queries) CountCompletedPlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedPlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompletedPlansToday = `-- name: CountCompletedPlansToday :one
SELECT COUNT(*) FROM load_plans 
WHERE status = 'COMPLETED' 
AND created_at >= CURRENT_DATE
`

func (q *Queries) CountCompletedPlansToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedPlansToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContainers = `-- name: CountContainers :one
SELECT COUNT(*) FROM containers
`

func (q *Queries) CountContainers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countContainers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalItems = `-- name: CountTotalItems :one
SELECT COALESCE(SUM(quantity), 0)::BIGINT FROM load_items
`

func (q *Queries) CountTotalItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalItems)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countTotalUsers = `-- name: CountTotalUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountTotalUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAvgVolumeUtilization = `-- name: GetAvgVolumeUtilization :one
SELECT COALESCE(AVG(volume_utilization_pct), 0)::FLOAT
FROM plan_results
`

func (q *Queries) GetAvgVolumeUtilization(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, getAvgVolumeUtilization)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const getPlanStatusDistribution = `-- name: GetPlanStatusDistribution :many
SELECT status, COUNT(*) as count 
FROM load_plans 
GROUP BY status
`

type GetPlanStatusDistributionRow struct {
	Status *string `json:"status"`
	Count  int64   `json:"count"`
}

func (q *Queries) GetPlanStatusDistribution(ctx context.Context) ([]GetPlanStatusDistributionRow, error) {
	rows, err := q.db.Query(ctx, getPlanStatusDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlanStatusDistributionRow
	for rows.Next() {
		var i GetPlanStatusDistributionRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
