// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: member.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (
    workspace_id,
    user_id,
    role_id
) VALUES (
    $1, $2, $3
)
RETURNING member_id, workspace_id, user_id, role_id, created_at, updated_at
`

type CreateMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	RoleID      uuid.UUID `json:"role_id"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember, arg.WorkspaceID, arg.UserID, arg.RoleID)
	var i Member
	err := row.Scan(
		&i.MemberID,
		&i.WorkspaceID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members
WHERE member_id = $1
  AND workspace_id = $2
`

type DeleteMemberParams struct {
	MemberID    uuid.UUID `json:"member_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.MemberID, arg.WorkspaceID)
	return err
}

const getMember = `-- name: GetMember :one
SELECT member_id, workspace_id, user_id, role_id, created_at, updated_at
FROM members
WHERE member_id = $1
`

func (q *Queries) GetMember(ctx context.Context, memberID uuid.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, memberID)
	var i Member
	err := row.Scan(
		&i.MemberID,
		&i.WorkspaceID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberByWorkspaceAndUser = `-- name: GetMemberByWorkspaceAndUser :one
SELECT member_id, workspace_id, user_id, role_id, created_at, updated_at
FROM members
WHERE workspace_id = $1
  AND user_id = $2
`

type GetMemberByWorkspaceAndUserParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMemberByWorkspaceAndUser(ctx context.Context, arg GetMemberByWorkspaceAndUserParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByWorkspaceAndUser, arg.WorkspaceID, arg.UserID)
	var i Member
	err := row.Scan(
		&i.MemberID,
		&i.WorkspaceID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberRoleNameByWorkspaceAndUser = `-- name: GetMemberRoleNameByWorkspaceAndUser :one
SELECT r.name AS role_name
FROM members m
JOIN roles r ON r.role_id = m.role_id
WHERE m.workspace_id = $1
  AND m.user_id = $2
`

type GetMemberRoleNameByWorkspaceAndUserParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMemberRoleNameByWorkspaceAndUser(ctx context.Context, arg GetMemberRoleNameByWorkspaceAndUserParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRoleNameByWorkspaceAndUser, arg.WorkspaceID, arg.UserID)
	var role_name string
	err := row.Scan(&role_name)
	return role_name, err
}

const listMembersByWorkspace = `-- name: ListMembersByWorkspace :many
SELECT
    m.member_id,
    m.workspace_id,
    m.user_id,
    m.role_id,
    r.name AS role_name,
    u.username,
    u.email,
    m.created_at,
    m.updated_at
FROM members m
JOIN users u ON u.user_id = m.user_id
JOIN roles r ON r.role_id = m.role_id
WHERE m.workspace_id = $1
ORDER BY m.created_at ASC
LIMIT $2 OFFSET $3
`

type ListMembersByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

type ListMembersByWorkspaceRow struct {
	MemberID    uuid.UUID `json:"member_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	RoleID      uuid.UUID `json:"role_id"`
	RoleName    string    `json:"role_name"`
	Username    string    `json:"username"`
	Email       string    `json:"email"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListMembersByWorkspace(ctx context.Context, arg ListMembersByWorkspaceParams) ([]ListMembersByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listMembersByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersByWorkspaceRow
	for rows.Next() {
		var i ListMembersByWorkspaceRow
		if err := rows.Scan(
			&i.MemberID,
			&i.WorkspaceID,
			&i.UserID,
			&i.RoleID,
			&i.RoleName,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE members
SET
    role_id = $3,
    updated_at = NOW()
WHERE member_id = $1
  AND workspace_id = $2
`

type UpdateMemberRoleParams struct {
	MemberID    uuid.UUID `json:"member_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	RoleID      uuid.UUID `json:"role_id"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.MemberID, arg.WorkspaceID, arg.RoleID)
	return err
}
