// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Container struct {
	ContainerID   uuid.UUID        `json:"container_id"`
	Name          string           `json:"name"`
	InnerLengthMm pgtype.Numeric   `json:"inner_length_mm"`
	InnerWidthMm  pgtype.Numeric   `json:"inner_width_mm"`
	InnerHeightMm pgtype.Numeric   `json:"inner_height_mm"`
	MaxWeightKg   pgtype.Numeric   `json:"max_weight_kg"`
	Description   *string          `json:"description"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	WorkspaceID   *uuid.UUID       `json:"workspace_id"`
}

type Invite struct {
	InviteID        uuid.UUID  `json:"invite_id"`
	WorkspaceID     uuid.UUID  `json:"workspace_id"`
	Email           string     `json:"email"`
	RoleID          uuid.UUID  `json:"role_id"`
	TokenHash       string     `json:"token_hash"`
	InvitedByUserID uuid.UUID  `json:"invited_by_user_id"`
	ExpiresAt       *time.Time `json:"expires_at"`
	AcceptedAt      time.Time  `json:"accepted_at"`
	RevokedAt       time.Time  `json:"revoked_at"`
	CreatedAt       time.Time  `json:"created_at"`
}

type LoadItem struct {
	ItemID        uuid.UUID      `json:"item_id"`
	PlanID        *uuid.UUID     `json:"plan_id"`
	ItemLabel     *string        `json:"item_label"`
	LengthMm      pgtype.Numeric `json:"length_mm"`
	WidthMm       pgtype.Numeric `json:"width_mm"`
	HeightMm      pgtype.Numeric `json:"height_mm"`
	WeightKg      pgtype.Numeric `json:"weight_kg"`
	Quantity      int32          `json:"quantity"`
	AllowRotation *bool          `json:"allow_rotation"`
	ColorHex      *string        `json:"color_hex"`
}

type LoadPlan struct {
	PlanID        uuid.UUID        `json:"plan_id"`
	PlanCode      string           `json:"plan_code"`
	Status        *string          `json:"status"`
	ContLabel     *string          `json:"cont_label"`
	LengthMm      pgtype.Numeric   `json:"length_mm"`
	WidthMm       pgtype.Numeric   `json:"width_mm"`
	HeightMm      pgtype.Numeric   `json:"height_mm"`
	MaxWeightKg   pgtype.Numeric   `json:"max_weight_kg"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	CreatedByType string           `json:"created_by_type"`
	CreatedByID   uuid.UUID        `json:"created_by_id"`
	WorkspaceID   *uuid.UUID       `json:"workspace_id"`
}

type Member struct {
	MemberID    uuid.UUID `json:"member_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	RoleID      uuid.UUID `json:"role_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Permission struct {
	PermissionID uuid.UUID `json:"permission_id"`
	Name         string    `json:"name"`
	Description  *string   `json:"description"`
	CreatedAt    time.Time `json:"created_at"`
}

type PlanPlacement struct {
	PlacementID  uuid.UUID      `json:"placement_id"`
	ResultID     *uuid.UUID     `json:"result_id"`
	ItemID       *uuid.UUID     `json:"item_id"`
	PosX         pgtype.Numeric `json:"pos_x"`
	PosY         pgtype.Numeric `json:"pos_y"`
	PosZ         pgtype.Numeric `json:"pos_z"`
	RotationCode *int32         `json:"rotation_code"`
	StepNumber   int32          `json:"step_number"`
}

type PlanResult struct {
	ResultID             uuid.UUID        `json:"result_id"`
	PlanID               *uuid.UUID       `json:"plan_id"`
	TotalLoadedWeightKg  pgtype.Numeric   `json:"total_loaded_weight_kg"`
	VolumeUtilizationPct pgtype.Numeric   `json:"volume_utilization_pct"`
	IsFeasible           *bool            `json:"is_feasible"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
}

type PlatformMember struct {
	UserID    uuid.UUID `json:"user_id"`
	RoleID    uuid.UUID `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Product struct {
	ProductID   uuid.UUID        `json:"product_id"`
	Name        string           `json:"name"`
	LengthMm    pgtype.Numeric   `json:"length_mm"`
	WidthMm     pgtype.Numeric   `json:"width_mm"`
	HeightMm    pgtype.Numeric   `json:"height_mm"`
	WeightKg    pgtype.Numeric   `json:"weight_kg"`
	ColorHex    *string          `json:"color_hex"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	WorkspaceID *uuid.UUID       `json:"workspace_id"`
}

type RefreshToken struct {
	Token       string     `json:"token"`
	UserID      uuid.UUID  `json:"user_id"`
	ExpiresAt   *time.Time `json:"expires_at"`
	RevokedAt   time.Time  `json:"revoked_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
}

type Role struct {
	RoleID      uuid.UUID `json:"role_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type User struct {
	UserID       uuid.UUID `json:"user_id"`
	RoleID       uuid.UUID `json:"role_id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type UserProfile struct {
	ProfileID   uuid.UUID   `json:"profile_id"`
	UserID      uuid.UUID   `json:"user_id"`
	FullName    *string     `json:"full_name"`
	Gender      *string     `json:"gender"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	PhoneNumber *string     `json:"phone_number"`
	Address     *string     `json:"address"`
	AvatarUrl   *string     `json:"avatar_url"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type Workspace struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Type        string    `json:"type"`
	Name        string    `json:"name"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
