// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	PermissionID uuid.UUID `json:"permission_id"`
	Name         string    `json:"name"`
	Description  *string   `json:"description"`
	CreatedAt    time.Time `json:"created_at"`
}

type RefreshToken struct {
	Token     string     `json:"token"`
	UserID    uuid.UUID  `json:"user_id"`
	ExpiresAt *time.Time `json:"expires_at"`
	RevokedAt time.Time  `json:"revoked_at"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type Role struct {
	RoleID      uuid.UUID `json:"role_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type User struct {
	UserID       uuid.UUID `json:"user_id"`
	RoleID       uuid.UUID `json:"role_id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type UserProfile struct {
	ProfileID   uuid.UUID   `json:"profile_id"`
	UserID      uuid.UUID   `json:"user_id"`
	FullName    *string     `json:"full_name"`
	Gender      *string     `json:"gender"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	PhoneNumber *string     `json:"phone_number"`
	Address     *string     `json:"address"`
	AvatarUrl   *string     `json:"avatar_url"`
	UpdatedAt   time.Time   `json:"updated_at"`
}
