// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (
    name, 
    description
) VALUES (
    $1, 
    $2
)
RETURNING permission_id, name, description, created_at
`

type CreatePermissionParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.Name, arg.Description)
	var i Permission
	err := row.Scan(
		&i.PermissionID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions 
WHERE permission_id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, permissionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePermission, permissionID)
	return err
}

const getPermission = `-- name: GetPermission :one
SELECT permission_id, name, description, created_at
FROM permissions
WHERE permission_id = $1
`

func (q *Queries) GetPermission(ctx context.Context, permissionID uuid.UUID) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermission, permissionID)
	var i Permission
	err := row.Scan(
		&i.PermissionID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT permission_id, name, description, created_at
FROM permissions
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListPermissionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.PermissionID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermission = `-- name: UpdatePermission :exec
UPDATE permissions 
SET 
    name = $2,
    description = $3
WHERE permission_id = $1
`

type UpdatePermissionParams struct {
	PermissionID uuid.UUID `json:"permission_id"`
	Name         string    `json:"name"`
	Description  *string   `json:"description"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error {
	_, err := q.db.Exec(ctx, updatePermission, arg.PermissionID, arg.Name, arg.Description)
	return err
}
