// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plan_ownership.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const claimPlansFromGuest = `-- name: ClaimPlansFromGuest :exec
UPDATE load_plans
SET created_by_type = 'user',
    created_by_id = $1,
    workspace_id = $2
WHERE created_by_type = 'guest'
  AND created_by_id = $3
`

type ClaimPlansFromGuestParams struct {
	UserID      uuid.UUID  `json:"user_id"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
	GuestID     uuid.UUID  `json:"guest_id"`
}

func (q *Queries) ClaimPlansFromGuest(ctx context.Context, arg ClaimPlansFromGuestParams) error {
	_, err := q.db.Exec(ctx, claimPlansFromGuest, arg.UserID, arg.WorkspaceID, arg.GuestID)
	return err
}

const countPlansByCreator = `-- name: CountPlansByCreator :one
SELECT COUNT(*)
FROM load_plans
WHERE created_by_type = $1
  AND created_by_id = $2
`

type CountPlansByCreatorParams struct {
	CreatedByType string    `json:"created_by_type"`
	CreatedByID   uuid.UUID `json:"created_by_id"`
}

func (q *Queries) CountPlansByCreator(ctx context.Context, arg CountPlansByCreatorParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPlansByCreator, arg.CreatedByType, arg.CreatedByID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
