// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_member.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getPlatformRoleByUserID = `-- name: GetPlatformRoleByUserID :one
SELECT r.name AS role_name
FROM platform_members pm
JOIN roles r ON r.role_id = pm.role_id
WHERE pm.user_id = $1
`

func (q *Queries) GetPlatformRoleByUserID(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPlatformRoleByUserID, userID)
	var role_name string
	err := row.Scan(&role_name)
	return role_name, err
}

const upsertPlatformMember = `-- name: UpsertPlatformMember :exec
INSERT INTO platform_members (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET role_id = EXCLUDED.role_id
`

type UpsertPlatformMemberParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) UpsertPlatformMember(ctx context.Context, arg UpsertPlatformMemberParams) error {
	_, err := q.db.Exec(ctx, upsertPlatformMember, arg.UserID, arg.RoleID)
	return err
}
