// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name, 
    length_mm, 
    width_mm, 
    height_mm, 
    weight_kg, 
    color_hex
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING product_id, name, length_mm, width_mm, height_mm, weight_kg, color_hex, created_at, updated_at
`

type CreateProductParams struct {
	Name     string         `json:"name"`
	LengthMm pgtype.Numeric `json:"length_mm"`
	WidthMm  pgtype.Numeric `json:"width_mm"`
	HeightMm pgtype.Numeric `json:"height_mm"`
	WeightKg pgtype.Numeric `json:"weight_kg"`
	ColorHex *string        `json:"color_hex"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.LengthMm,
		arg.WidthMm,
		arg.HeightMm,
		arg.WeightKg,
		arg.ColorHex,
	)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.LengthMm,
		&i.WidthMm,
		&i.HeightMm,
		&i.WeightKg,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products 
WHERE product_id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, productID)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT product_id, name, length_mm, width_mm, height_mm, weight_kg, color_hex, created_at, updated_at
FROM products
WHERE product_id = $1
`

func (q *Queries) GetProduct(ctx context.Context, productID uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, productID)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.LengthMm,
		&i.WidthMm,
		&i.HeightMm,
		&i.WeightKg,
		&i.ColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT product_id, name, length_mm, width_mm, height_mm, weight_kg, color_hex, created_at, updated_at
FROM products
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.LengthMm,
			&i.WidthMm,
			&i.HeightMm,
			&i.WeightKg,
			&i.ColorHex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products 
SET 
    name = $2,
    length_mm = $3,
    width_mm = $4,
    height_mm = $5,
    weight_kg = $6,
    color_hex = $7,
    updated_at = NOW()
WHERE product_id = $1
`

type UpdateProductParams struct {
	ProductID uuid.UUID      `json:"product_id"`
	Name      string         `json:"name"`
	LengthMm  pgtype.Numeric `json:"length_mm"`
	WidthMm   pgtype.Numeric `json:"width_mm"`
	HeightMm  pgtype.Numeric `json:"height_mm"`
	WeightKg  pgtype.Numeric `json:"weight_kg"`
	ColorHex  *string        `json:"color_hex"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.ProductID,
		arg.Name,
		arg.LengthMm,
		arg.WidthMm,
		arg.HeightMm,
		arg.WeightKg,
		arg.ColorHex,
	)
	return err
}
