// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddLoadItem(ctx context.Context, arg AddLoadItemParams) (LoadItem, error)
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	ClaimPlansFromGuest(ctx context.Context, arg ClaimPlansFromGuestParams) error
	CountActivePlans(ctx context.Context) (int64, error)
	CountCompletedPlans(ctx context.Context) (int64, error)
	CountCompletedPlansToday(ctx context.Context) (int64, error)
	CountContainers(ctx context.Context) (int64, error)
	CountPlansByCreator(ctx context.Context, arg CountPlansByCreatorParams) (int64, error)
	CountTotalItems(ctx context.Context) (int64, error)
	CountTotalUsers(ctx context.Context) (int64, error)
	CreateContainer(ctx context.Context, arg CreateContainerParams) (Container, error)
	CreateLoadPlan(ctx context.Context, arg CreateLoadPlanParams) (LoadPlan, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreatePlanPlacement(ctx context.Context, arg []CreatePlanPlacementParams) (int64, error)
	CreatePlanResult(ctx context.Context, arg CreatePlanResultParams) (PlanResult, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteContainer(ctx context.Context, containerID uuid.UUID) error
	DeleteLoadItem(ctx context.Context, arg DeleteLoadItemParams) error
	DeleteLoadPlan(ctx context.Context, planID uuid.UUID) error
	DeletePermission(ctx context.Context, permissionID uuid.UUID) error
	DeletePlanResults(ctx context.Context, planID *uuid.UUID) error
	DeleteProduct(ctx context.Context, productID uuid.UUID) error
	DeleteRole(ctx context.Context, roleID uuid.UUID) error
	DeleteRolePermissions(ctx context.Context, roleID uuid.UUID) error
	DeleteUser(ctx context.Context, userID uuid.UUID) error
	GetAvgVolumeUtilization(ctx context.Context) (float64, error)
	GetContainer(ctx context.Context, containerID uuid.UUID) (Container, error)
	GetLoadItem(ctx context.Context, arg GetLoadItemParams) (LoadItem, error)
	GetLoadPlan(ctx context.Context, planID uuid.UUID) (LoadPlan, error)
	GetLoadPlanForGuest(ctx context.Context, arg GetLoadPlanForGuestParams) (LoadPlan, error)
	GetPermission(ctx context.Context, permissionID uuid.UUID) (Permission, error)
	GetPermissionsByRole(ctx context.Context, name string) ([]string, error)
	GetPlanResult(ctx context.Context, planID *uuid.UUID) (PlanResult, error)
	GetPlanStatusDistribution(ctx context.Context) ([]GetPlanStatusDistributionRow, error)
	GetProduct(ctx context.Context, productID uuid.UUID) (Product, error)
	GetRefreshToken(ctx context.Context, token string) (GetRefreshTokenRow, error)
	GetRole(ctx context.Context, roleID uuid.UUID) (Role, error)
	GetRoleByName(ctx context.Context, name string) (GetRoleByNameRow, error)
	GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]uuid.UUID, error)
	GetUserByID(ctx context.Context, userID uuid.UUID) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	ListContainers(ctx context.Context, arg ListContainersParams) ([]Container, error)
	ListLoadItems(ctx context.Context, planID *uuid.UUID) ([]LoadItem, error)
	ListLoadPlans(ctx context.Context, arg ListLoadPlansParams) ([]LoadPlan, error)
	ListLoadPlansForGuest(ctx context.Context, arg ListLoadPlansForGuestParams) ([]LoadPlan, error)
	ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]Permission, error)
	ListPlanPlacements(ctx context.Context, resultID *uuid.UUID) ([]PlanPlacement, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	RevokeRefreshToken(ctx context.Context, token string) error
	UpdateContainer(ctx context.Context, arg UpdateContainerParams) error
	UpdateLoadItem(ctx context.Context, arg UpdateLoadItemParams) error
	UpdateLoadPlan(ctx context.Context, arg UpdateLoadPlanParams) error
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error
	UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
