// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    role_id, 
    username, 
    email, 
    password_hash
) VALUES (
    $1, 
    $2, 
    $3, 
    $4
)
RETURNING  user_id, role_id, username, email, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.RoleID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.RoleID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT role_id, name, description FROM roles
WHERE name = $1
`

type GetRoleByNameRow struct {
	RoleID      uuid.UUID `json:"role_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

func (q *Queries) GetRoleByName(ctx context.Context, name string) (GetRoleByNameRow, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i GetRoleByNameRow
	err := row.Scan(&i.RoleID, &i.Name, &i.Description)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    u.user_id,
    u.username,
    u.email,
    r.name AS role_name,
    up.full_name,
    up.gender,
    up.date_of_birth,
    up.phone_number,
    up.address,
    up.avatar_url
FROM users u
JOIN roles r ON u.role_id = r.role_id
LEFT JOIN user_profiles up ON up.user_id = u.user_id
WHERE u.user_id = $1
`

type GetUserByIDRow struct {
	UserID      uuid.UUID   `json:"user_id"`
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	RoleName    string      `json:"role_name"`
	FullName    *string     `json:"full_name"`
	Gender      *string     `json:"gender"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	PhoneNumber *string     `json:"phone_number"`
	Address     *string     `json:"address"`
	AvatarUrl   *string     `json:"avatar_url"`
}

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.RoleName,
		&i.FullName,
		&i.Gender,
		&i.DateOfBirth,
		&i.PhoneNumber,
		&i.Address,
		&i.AvatarUrl,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT u.user_id, u.username, u.email, u.password_hash, u.role_id, r.name AS role_name
FROM users u
JOIN roles r ON u.role_id = r.role_id
WHERE u.username = $1 AND u.is_active = true
`

type GetUserByUsernameRow struct {
	UserID       uuid.UUID `json:"user_id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	RoleID       uuid.UUID `json:"role_id"`
	RoleName     string    `json:"role_name"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.RoleName,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT 
    u.user_id,
    u.username,
    u.email,
    r.name AS role_name,
    up.full_name,
    up.phone_number,
    u.created_at
FROM users u
JOIN roles r ON u.role_id = r.role_id
LEFT JOIN user_profiles up ON up.user_id = u.user_id
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	UserID      uuid.UUID `json:"user_id"`
	Username    string    `json:"username"`
	Email       string    `json:"email"`
	RoleName    string    `json:"role_name"`
	FullName    *string   `json:"full_name"`
	PhoneNumber *string   `json:"phone_number"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.RoleName,
			&i.FullName,
			&i.PhoneNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users 
SET 
    role_id = $2,
    email = $3,
    username = $4,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserParams struct {
	UserID   uuid.UUID `json:"user_id"`
	RoleID   uuid.UUID `json:"role_id"`
	Email    string    `json:"email"`
	Username string    `json:"username"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.UserID,
		arg.RoleID,
		arg.Email,
		arg.Username,
	)
	return err
}
