// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type Container struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	LengthMm    float64   `json:"length_mm"`
	WidthMm     float64   `json:"width_mm"`
	HeightMm    float64   `json:"height_mm"`
	MaxWeightKg float64   `json:"max_weight_kg"`
	CreatedAt   time.Time `json:"created_at"`
}

type Placement struct {
	ID         uuid.UUID `json:"id"`
	PlanID     uuid.UUID `json:"plan_id"`
	ProductID  uuid.UUID `json:"product_id"`
	PosX       float64   `json:"pos_x"`
	PosY       float64   `json:"pos_y"`
	PosZ       float64   `json:"pos_z"`
	Rotation   int32     `json:"rotation"`
	StepNumber int32     `json:"step_number"`
}

type Plan struct {
	ID           uuid.UUID `json:"id"`
	ContainerID  uuid.UUID `json:"container_id"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	CalculatedAt time.Time `json:"calculated_at"`
}

type PlanItem struct {
	ID        uuid.UUID `json:"id"`
	PlanID    uuid.UUID `json:"plan_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
}

type Product struct {
	ID        uuid.UUID `json:"id"`
	Label     string    `json:"label"`
	Sku       string    `json:"sku"`
	LengthMm  float64   `json:"length_mm"`
	WidthMm   float64   `json:"width_mm"`
	HeightMm  float64   `json:"height_mm"`
	WeightKg  float64   `json:"weight_kg"`
	CreatedAt time.Time `json:"created_at"`
}
